import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Nightreign Router",
  description: "Generated by create-t3-app",
  icons: [
    { rel: "icon", url: "/favicon_io/favicon.ico" },
    { rel: "icon", type: "image/png", sizes: "32x32", url: "/favicon_io/favicon-32x32.png" },
    { rel: "icon", type: "image/png", sizes: "16x16", url: "/favicon_io/favicon-16x16.png" },
    { rel: "apple-touch-icon", sizes: "180x180", url: "/favicon_io/apple-touch-icon.png" },
    { rel: "manifest", url: "/favicon_io/site.webmanifest" },
    { rel: "icon", type: "image/png", sizes: "192x192", url: "/favicon_io/android-chrome-192x192.png" },
    { rel: "icon", type: "image/png", sizes: "512x512", url: "/favicon_io/android-chrome-512x512.png" },
  ],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Analytics />
      </body>
    </html>
  );
}
